---
- name: "Read repo packages in {{ repo }}"
  ansible.builtin.command: "aptly repo -with-packages -json show {{ repo }}"
  register: repo_info_raw

- name: Take repo packages
  ansible.builtin.set_fact:
    repo_info: "{{ (repo_info_raw.stdout | from_json) }}"

- name: "Show packages in {{ repo }}"
  ansible.builtin.debug:
    msg: "{{ repo_info.Packages }}"

- name: Prepare Listing
  ansible.builtin.template:
    src: repo.html.j2
    dest: "{{ repo_public }}/{{ repo }}.html"
    mode: "0644"
